### ISSUE TITLE
Templates for onRender

### ISSUE THREAD

**Issue by hxtree** [Ouxsoft/LivingMarkup#30]
Should a template file be used instead of including return in onRender?

**Comment by aswinvk28** [comment]
**hxtree** won't require a template **onRender** because there is no replication of content throughout. This requires administration and the complexity improves as you include more flexibility in the production of templates. If content types are added, they must conform with administration of content.

Please check here:
https://refactoring.guru/design-patterns/chain-of-responsibility

Why don't you try code generation based on UI / Graphical Interface? 
![https://www.drupal.org/files/OneTemplate.jpg](https://www.drupal.org/files/OneTemplate.jpg)

**Comment by hxtree** [comment]
Hi Awsin,

The question I don't know the answer to is whether an onRender call could consist of enough markup to justify it being broken up into another a View (*.phtml) type file for separation of concerns? For example, what would a bloated Module/Navbar onRender() look like? I'd rather keep it simple, of course, but it certainly something to consider.

I'm both familiar with the Refactoring Guru and the Chain of Responsibility design pattern. However, reading through it again, got me to think about applying a chain of responsibility to DOM elements, which could be pretty neat for forms.

e.g. button onSubmit could be picked up by a module with xpath \\form using the design pattern. This inline with the way the DOM ancestor variable access currently works.
```
<form>
<button/>
<form>
```

I certainly see the benefits of a WYSIWYG implementation. But, first I think it's important to flesh out the core modules.

**Comment by hxtree** [comment]
Also, I see the page templates you're referring to being essentially just a boilerplate page that gets copied over during page creation that consist of LHTML5.

**Comment by hxtree** [comment]
Page templates should feature semantic elements:
https://www.w3schools.com/html/html5_semantic_elements.asp
